spring:
  application:
    name: microservice-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8091/eureka/#,http://localhost:8092/eureka/
  instance:
    prefer-ip-address: true #若为false，则将操作系统的hostname注册到eurekaserver，true则注册ip到eurekaserver    

server:
  port: 8081

#---
#spring:
#  profiles: u1
#server:
#  port: 8081
#
#---
#spring:
#  profiles: u2
#server:
#  port: 8082
#
#---
#spring:
#  profiles: u3
#server:
#  port: 8083  