server:
  port: 8091
management:
  security:
    enabled: false
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/